name: CI - Pytest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Prefer installing your package (src/rice_ml) via pyproject
          if [ -f pyproject.toml ]; then
            pip install -e .
          fi
          # Optional: also honor requirements.txt if present
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure pytest is available
          pip install pytest

      - name: Run pytest
        env:
          # Make sure imports like `from rice_ml import ...` work even without editable install
          PYTHONPATH: src
        run: |
          pytest -v --maxfail=1 --disable-warnings tests
